### ISSUE TITLE
Update Bounty schema with claimantPullRequest

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-API#4]
Dependency of OpenQDev/OpenQ-Frontend#336

**DESCRIPTION**

Update the [Bounty schema](https://github.com/OpenQDev/OpenQ-API/blob/development/prisma/schema.prisma) with a field called `claimantPullRequest`

This field should be null until it is updated.

An additional update will have to be added to the [updateBounty resolver](https://github.com/OpenQDev/OpenQ-API/blob/development/src/resolvers.js#L96) as well.

**DATA STRUCTURES**

The `claimantPullRequest` should be of type `PullRequest`

On `Bounty`, the `claimantPullRequest` should be nullable (aka not required).

```javascript
type PullRequest {
   url: String!
   author: String!
   mergedAt: Date!
}

type Bounty {
   ...
   claimantPullRequest: PullRequest
   ...
}
```

**ACCEPTANCE CRITERIA**

We should be able to go to the GraphQL playground, send a mutation to `updateBounty` with a new `claimantPullRequest`, and see the change persisted.

**RESOURCES**

Set up your own MongoDB sandbox by following the instructions in this repository's README

**QUESTIONS**

Does Prisma/GraphQL natively support a URI data type?

**Comment by Terry-404** [comment]
- **Prisma** in MongoDB doesn't natively support URI Date Type,
- **GraphQL** too doesn't "natively" support URI Data type but we can use **Scalars** to make a Custom URI Data Type and specify everything about it in resolvers.
